### ISSUE TITLE
Hard dependency on projectile

### ISSUE THREAD

**Issue by danrharms** [thiderman/makefile-executor.el#2]
A soft dependency on projectile would allow this library to be usable even by those who dare not to use projectile.  The changes are minimal:

1. soft require
`(require 'projectile nil t)`

2. conditional protection around definition of `(def-projectile-commander-method ?m`
`(when (featurep 'projectile)`

**Comment by thiderman** [comment]
One of the main features of `(makefile-executor-execute-project-target)` is that it uses `(projectile-current-project-files)` to find makefiles relevant to the project. What would you suggest we fall back to when projectile is not available?

**Comment by danrharms** [comment]
I was under the impression that the purpose of the library was to provide helpful utilities when editing makefiles. The projectile interface is merely a convenient way to gather makefiles to be edited. Of course even that is not the only way to open a makefile, even for projectile users. 

So to answer your question, I was thinking that in my case I would never call (makefile-executor-execute-project-target), and accordingly the list of files could be empty.

The question is, do you want your library to be of use even for those who do not use projectile. I was hoping the answer was yes, especially in light of the relatively tiny footprint of projectile in your library's code.

**Comment by thiderman** [comment]
You are correct, of course. My perspective is a bit clouded because this project started as just the projectile extensions and the name was `projectile-makefile` at first. I'll wrap the stuff you mention and make a PR!
